base_url: "https://api.tfl.gov.uk:443"

local_stations:
  wood_green_underground:
    id: "940GZZLUWOG"
    name: "Wood Green"
    short_name: "Wd Grn"
    code: "WGN"
    mode: "tube"
    services:
      - line: "piccadilly"
        platform: "WestBound - Platform 2"
        direction: "West"
      - line: "piccadilly"
        platform: "EastBound - Platform 1"
        direction: "East"

  palmers_green_stop_h:
    id: "490010736H"
    name: "Palmers Green"
    short_name: "Trngle"
    code: ""
    mode: "bus"
    services:
      - line: "329"
        platform: "H"
        direction: 
      - line: "121"
        platform: "H"
      - line: "n29"
        platform: "H"

# https://api.tfl.gov.uk/line/mode/national-rail/status
# https://api.tfl.gov.uk/line/great-northern/stoppoints
  # palmers_green_railway:
  #   id: "490G000097H"
  #   name: "Palmers Green Railway Station"
  #   short_name: "Palmers Green"
  #   mode: "rail"
  #   services:
  #     - platforms: [1, 2]